[package]
name = "lpad"
version = "1.0.0"
edition = "2018"
keywords = ["lpad"]
description = "Left-pad each line in a string"
license = "MIT"
homepage = "https://github.com/junderw/lpad-rust"
documentation = "https://docs.rs/crate/lpad"
repository = "https://github.com/junderw/lpad-rust"
